### ISSUE TITLE
Add "conflicts" to composer.json schema

### ISSUE THREAD

**Issue by mortenpless** [NamelessCoder/inline_page_editing#3]
As the extension conflicts with t3editor, we should reflect this in -composer.json- // ext_emconf.php

**Comment by NamelessCoder** [comment]
I would rather not declare this one as a strict conflict since it only affects a single type of field. We might instead make a condition that avoids enabling the inline editing for the `html` CType if `t3editor` is loaded. How does that sound as an alternative?
